### ISSUE TITLE
Change photo

### ISSUE THREAD

**Issue by Real-4339** [ValentynIpolitov/decor-haus#20]
Change photo near floor constructon 
In file: 2a880d532d41aae7f6d9a00c4481b835cda59368
![podlahovy-system-SIP-panel-1024x603](https://user-images.githubusercontent.com/71652431/187243665-73e50113-b052-4f07-a20b-897eb319cb8a.jpg)
![podlahovy-system-SIP-panelove-stavby-1024x603](https://user-images.githubusercontent.com/71652431/187243673-f45fd482-3cdc-4b9b-9a0f-bf65b9df2165.jpg)
[resources/js/Pages/Technologies.vue](https://github.com/ValentynIpolitov/decor-haus/commit/2a880d532d41aae7f6d9a00c4481b835cda59368#diff-d1759fee31ad606ecc691998adc968fb72b12ff30d49ad33e124a5914574b6ea)

**Comment by developer-irfan** [comment]
Assign me this task so i change the photo.
