### ISSUE TITLE
Images in materials page

### ISSUE THREAD

**Issue by ValentynIpolitov** [ValentynIpolitov/decor-haus#23]
Missing images lists:

1. outdoor products (3/last section in services)
- all photo

Need to add photos in folder /public/images/Pages/services/
and then add them to subpage Services
In Services.vue already prepeared 9 image sets, 3 of them ready(could be as inspiration), 5 sets left

**Comment by Real-4339** [comment]
outdoor products (3/last section in services)  - you mean PASIFIC – Motorized ?
